### ISSUE TITLE
BUG: @mouseover not working

### ISSUE THREAD

**Issue by dein0s** [DennisWG/Roid-Macros#28]
I've following macro that was working well with 'CastModifiers':
```
/script if nil then CastSpellByName("Flash Heal") end
/cast [mod:shift @player] Flash Heal; [mod:ctrl @mouseover] Flash Heal(Rank 4); [@mouseover] Flash Heal
```

But after I've switched to the newest version of 'Roid-Macros' it stopped working when I hover above player and target unitframes (haven't tested all other yet).

My current addon setup:
https://github.com/Aviana/LunaUnitFrames/commit/b1ce6f56c032a24286380c308f697e9cb879706b
https://github.com/shagu/pfUI/commit/422dd58fb7df39fcc592b213c800f617db6c1462

The only modification I did for both 'CastModifiers' and 'Roid-Macros' is:
`if not pfUI or not pfUI.uf.player then `
at https://github.com/DennisWG/Roid-Macros/blob/master/Extensions/Mouseover/pfUI.lua#L74

**Comment by DennisWG** [comment]
Thank you for reporting this bug. I was able to fix it, so please make sure to re-download the latest version!
