### ISSUE TITLE
Spells are greyed out using these modifiers

### ISSUE THREAD

**Issue by typhirz** [DennisWG/Roid-Macros#34]
Trying to make a set of macros for priest healing. The icons themselves are greyed out as if I did not have enough mana to cast the spells, but I do. This makes it difficult to judge if I do have enough mana for a given spell. Plus, the keybinds do not go red in order to indicate that my target is out of range, which adds to the difficulty.

**Comment by DennisWG** [comment]
Hey,

[this is a known bug and in the documentation I've provided a workaround](https://denniswg.github.io/Roid-Macros/compatibility/#gray-button-fix). There's also another workaround posted by another user [here](https://github.com/DennisWG/Roid-Macros/issues/27#issuecomment-389656582) but I haven't tried that one myself.

Cheers
