### ISSUE TITLE
Cancelaura

### ISSUE THREAD

**Issue by Finrodi** [DennisWG/Roid-Macros#35]
Hey, looking through the documentation, I wasn't able to find a solution to cancel specific buffs I have (nowadays /cancelaura or with SuperMacro /unbuff). Any chance you can implement that? :)

**Comment by Zebouski** [comment]
Hi there @DennisWG , it looks like cancelaura isn't in the codebase right now? But you had marked this as done?

I and many others would looove this command to be added, even if it does have complications due to how the api is limited to just searching by icons...
