### ISSUE TITLE
grid related error

### ISSUE THREAD

**Issue by Nihlo** [DennisWG/Roid-Macros#42]
Hey, I get this grid related errors regularly while playing and on login. Have to say that I don't use grid and it worked perfectly before.
![grid](https://user-images.githubusercontent.com/26931653/49308338-49055680-f4d8-11e8-87e6-d0b66df45510.jpg)

and thanks for the mod, it's awesome

**Comment by Road-block** [comment]
#46 Sorry for the duplicate, I searched for NotGrid and only show this afterwards.
