### ISSUE TITLE
Exists / Noexists

### ISSUE THREAD

**Issue by Thunderba11** [DennisWG/Roid-Macros#43]
Hello, great addon. However it's usability is greatly limited by the absense of exists/noexists conditionals. I know that you can utilize those through lua scripting but that kinda defeats the purpose of the addon. Any chance those conditionals can be added in the near future?

**Comment by DennisWG** [comment]
It's already implicitly checked whether the target exists. I don't see a reason to not do this, so please let me know if there is.

This means that this macro
```lua
/cast [@mouseover] Healing Touch
```
is equivalent to retails
```lua
/cast [@mouseover exists] Healing Touch
```
