### ISSUE TITLE
[no]buff [no]mybuff

### ISSUE THREAD

**Issue by itshozer** [DennisWG/Roid-Macros#45]
So I was having an issue with one of my macros that used the "nobuff" conditionals and I believe the issue is because there is no way to encapsulate the name of the buff. 

So below was my following macro:

/script if nil then CastSpellByName("Ice Block"); end
#showtooltip Ice Block
/stopcasting
/cast [nobuff:Ice Block @player]Ice Block;[mod:alt]Ice Block

Basically I wanted to be able to spam Ice block and not cancel it. 

The problem is that it would not cast ice block on my self if i had "Ice Armor" on because it was just looking for the word "Ice". I tried the below macro as well and that didn't work either. 

/cast !Ice Block

I believe this is a bug and if there was a way for us to encapsulate the buff with some quotes that would solve the issue. My work around for now is to only look for the word "Block" so my current macro looks like this.

/script if nil then CastSpellByName("Ice Block"); end
#showtooltip Ice Block
/stopcasting
/cast **[nobuff:Block @player]**Ice Block;[mod:alt]Ice Block

hope this helps.

**Comment by DennisWG** [comment]
Hey,

as stated in the [documentation](https://denniswg.github.io/Roid-Macros/conditions/buffs/), you must replace white spaces with underscores and it should work fine!
