### ISSUE TITLE
/petattack

### ISSUE THREAD

**Issue by Calthaza** [DennisWG/Roid-Macros#49]
Hi there.

I seem to have problems getting /petattack to work.
I have the latest version, and extracted to the correct folder. Many of the other functions are working, but this one is not.

/Calthaza

**Comment by DennisWG** [comment]
Could you please provide the Macro you're using? Or is it just plain `/petattack`?

**Comment by Calthaza** [comment]
Hey man. I believe it was an error linked to using supermacro. Removed that, and now it is working 😊

 

/Calthaza

 

Fra: DennisWG <notifications@github.com> 
Sendt: 2. mai 2019 17:22
Til: DennisWG/Roid-Macros <Roid-Macros@noreply.github.com>
Kopi: Calthaza <calthaza@gmail.com>; Author <author@noreply.github.com>
Emne: Re: [DennisWG/Roid-Macros] /petattack (#49)

 

Could you please provide the Macro you're using? Or is it just plain /petattack?

**Comment by Calthaza** [comment]
I do however get this error at login:
![image](https://user-images.githubusercontent.com/42499956/57189338-ea705880-6f0d-11e9-86d4-01889fe361d7.png)

**Comment by DennisWG** [comment]
Okay, glad to hear that it's now working! The error you're now getting should've been resolved with the latest update. Could you please try and re-download the AddOn?

**Comment by Calthaza** [comment]
Thanks man, no errors with the latest update :)
