### ISSUE TITLE
Classic support?

### ISSUE THREAD

**Issue by Jakobud** [DennisWG/Roid-Macros#56]
Any luck on porting this to Classic? There are some really nice features that aren't in native Classic macros, like checking for the existence of buffs, debuffs, etc.

**Comment by dan-personal** [comment]
Retail/Classic macro system is much more restricted. The majority of what this addon is capable of doing is enabled by how unrestrictive (but complicated) macroing was in vanilla. It wouldn't be possible to implement anything beyond what is currently available in the classic macroing system.
