### ISSUE TITLE
Multiple Parameters of same Condition

### ISSUE THREAD

**Issue by amptie** [DennisWG/Roid-Macros#69]
Hey,

i really love your addon and I am using it on Turtle WoW.
I am trying to build a macro to refresh Demo Shout on the enemy target (as a warrior).
Since there is also the possibility of being Demoralizing Roar (Feral Druid) up on the target my normal macro using [nodebuff:Demoralizing_Shout] condition doesn't work properly, since it will spam Demo Shout, when Druids debuff is up.

In your documentation it is said, that conditions can be stacked up by separating them with a white space, but I can't figure out how to stack those two debuff names ending up in an AND-condition, where both debuffs may not be on the target to successfully complete the condition. I tried some ways like this:

/cast [nodebuff:Demoralizing_Shout nodebuff:Demoralizing_Roar] Demoralizing Shout
/cast [nodebuff:Demoralizing_Shout, nodebuff:Demoralizing_Roar] Demoralizing Shout
/cast [nodebuff:Demoralizing_Shout Demoralizing_Roar] Demoralizing Shout
/cast [nodebuff:Demoralizing_Shout/Demoralizing_Roar] Demoralizing Shout
/cast [nodebuff:Demoralizing_Shout] [nodebuff:Demoralizing_Roar] Demoralizing Shout

None of them does the magic. Is it even possible to get two parameters of the same condition into one AND-condition?

Best regards

**Comment by welpenhund** [comment]
/cast [nodebuff:Demoralizing_Shout,nodebuff:Demoralizing_Roar @target] Demoralizing Shout
is your answer, you forgot the parameter that it requires to check your target.
